### find packages
GET http://localhost:8080/api/packages
Accept: application/json


### update package
PUT http://localhost:8080/api/packages
Accept: application/json
Content-Type: application/json

{


}

### create package
POST http://localhost:8080/api/packages
Content-Type: application/json
Accept: application/json

{
  "weight": 4

}

###
GET http://localhost:8080/api/packages/shipment/{{shipmentId}}/
Accept: application/json

###
GET http://localhost:8080/api/packages/{{id}}
Accept: application/json

###
GET http://localhost:8080/api/addresses
Accept: application/json

###
POST http://localhost:8080/api/addresses
Content-Type: application/json
Accept: application/json
###
GET http://localhost:8080/api/addresses/counties
Accept: application/json

###
GET http://localhost:8080/api/addresses/countries
Accept: application/json

###
GET http://localhost:8080/api/addresses/{{id}}
Accept: application/json

###
DELETE http://localhost:8080/api/addresses/{{id}}
Content-Type: application/json
Accept: application/json
###
PUT http://localhost:8080/api/addresses/{{id}}/ie
Accept: application/json
Content-Type: application/json
###
PUT http://localhost:8080/api/addresses/{{id}}/non-ie
Content-Type: application/json
Accept: application/json
###
GET http://localhost:8080/api/shipments
Accept: application/json

###
PUT http://localhost:8080/api/shipments
Content-Type: application/json
Accept: application/json
###
POST http://localhost:8080/api/shipments
Content-Type: application/json
Accept: application/json